/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wzorce.projektowe;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author MajsterX
 */
public class TextFileViewer extends javax.swing.JFrame {

    /**
     * Creates new form TextFileViewer
     */
    public TextFileViewer() {
        initComponents();
        
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
        File folder1 = new File("Z:/Wzorce/1/"); // Replace with the actual path to your directory
        File[] files1 = folder1.listFiles();
        if (files1 != null) {
            for (File file1 : files1) {
                if (file1.isFile()) {
                    model1.addElement(file1.getAbsolutePath());
                }
            }
        }
        fileComboBox1.setModel(model1);
        
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        File folder2 = new File("Z:/Wzorce/2/"); // Replace with the actual path to your directory
        File[] files2 = folder2.listFiles();
        if (files2 != null) {
            for (File file2 : files2) {
                if (file2.isFile()) {
                    model2.addElement(file2.getAbsolutePath());
                }
            }
        }
        fileComboBox2.setModel(model2);
        
        DefaultComboBoxModel<String> model3 = new DefaultComboBoxModel<>();
        File folder3 = new File("Z:/Wzorce/3/"); // Replace with the actual path to your directory
        File[] files3 = folder3.listFiles();
        if (files3 != null) {
            for (File file3 : files3) {
                if (file3.isFile()) {
                    model3.addElement(file3.getAbsolutePath());
                }
            }
        }
        fileComboBox3.setModel(model3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fileComboBox1 = new javax.swing.JComboBox<>();
        fileComboBox2 = new javax.swing.JComboBox<>();
        fileComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("<Wybierz wzorzec projektowy>");
        jTextArea1.setToolTipText("");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        fileComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        fileComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileComboBox1ActionPerformed(evt);
            }
        });

        fileComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2" }));
        fileComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileComboBox2ActionPerformed(evt);
            }
        });

        fileComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3" }));
        fileComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileComboBox3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Wzorce kreacyjne");

        jLabel2.setText("Wzorce strukturalne");

        jLabel3.setText("Wzorce behawioralne");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(fileComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2))
                            .addComponent(fileComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(167, 167, 167))
                            .addComponent(fileComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fileComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fileComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fileComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileComboBox1ActionPerformed
        // TODO add your handling code here:
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource(); // Get the source of the event (JComboBox)
        String selectedFile = (String) comboBox.getSelectedItem(); // Get the selected item (file name)

        if (selectedFile != null) {
            File file = new File(selectedFile);
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                StringBuilder content = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n"); // Read each line and append to the content
                }
                jTextArea1.setText(content.toString()); // Set the content in the text area
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_fileComboBox1ActionPerformed

    private void fileComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileComboBox2ActionPerformed
        // TODO add your handling code here:
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource(); // Get the source of the event (JComboBox)
        String selectedFile = (String) comboBox.getSelectedItem(); // Get the selected item (file name)

        if (selectedFile != null) {
            File file = new File(selectedFile);
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                StringBuilder content = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n"); // Read each line and append to the content
                }
                jTextArea1.setText(content.toString()); // Set the content in the text area
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_fileComboBox2ActionPerformed

    private void fileComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileComboBox3ActionPerformed
        // TODO add your handling code here:
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource(); // Get the source of the event (JComboBox)
        String selectedFile = (String) comboBox.getSelectedItem(); // Get the selected item (file name)

        if (selectedFile != null) {
            File file = new File(selectedFile);
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                StringBuilder content = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n"); // Read each line and append to the content
                }
                jTextArea1.setText(content.toString()); // Set the content in the text area
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_fileComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextFileViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TextFileViewer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fileComboBox1;
    private javax.swing.JComboBox<String> fileComboBox2;
    private javax.swing.JComboBox<String> fileComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
